apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  cloudwatch.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "name": "cw-data-dev",            
                "editable": true,
                "type": "cloudwatch",               
                "jsonData":
                    {
                        "authType": "arn",
                        "defaultRegion": "ap-south-1",
                        "customMetricsNamespaces": "",
                        "assumeRoleArn": "arn:aws:iam::603461017249:role/grafana_role",
                    }				
            }
        ]
    }